### ISSUE TITLE
Display cross-sell items when a user is browsing a product

### ISSUE THREAD

**Issue by yujinlee0130** [CSCI-GA-2820-FA23-003/recommendations#1]
**As a** User
**I need** to see cross-sell items when I browse a product  
**So that** I can buy complementary items to purchase with a product I am currently interested in.
   
 ### Details and Assumptions
* A cross-sell item is a complementary item that is in a different product category but is frequently bought together with the current item
 * Use Python enumerations to represent the different recommendation types: Up-sell, Cross-sell, Accessories)
 * Display the name and the picture of the recommended products
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the cross-sell items exist in the database,
 When I browse a product,
 Then I should see at least 3 recommended items in the cross-sell category
```

**Comment by ceceyjwww** [comment]
Cross-selling is too vague. For user story, we might want it to be as specific as possible.
