### ISSUE TITLE
Create a new recommendation to the schema

### ISSUE THREAD

**Issue by yosemitii** [CSCI-GA-2820-FA23-003/recommendations#16]
**As an** developer
**I need to** link two unrelated products in data model
**So that** it can be shown related to users

Details and Assumptions
Administrators need to link the two products in the data model.

Acceptance Criteria
```
Given that we have a database
When a developer want to link two products
The API should handle the request and manage the database.
```

**Comment by ceceyjwww** [comment]
Changed the wording
