### ISSUE TITLE
Read a recommendation (GET)

### ISSUE THREAD

**Issue by yujinlee0130** [CSCI-GA-2820-FA23-003/recommendations#17]
**As a** developer
**I need** I need the ability to read recommendations for a product from the database
**So that** So that I can see the details for each recommended item
  
 ### Details and Assumptions
 * Each recommendation should have details such as product ID, category, price, product description, its relation to the queried item, and the recommendation weight. Reading a recommendation would return all these details.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that we have a model that returns recommendations for a product, 
 When a developer reads a recommendation
 Then he should be able to see all the details related to the recommendation
```

**Comment by ceceyjwww** [comment]
Looking great
