### ISSUE TITLE
Set Up Recommendation Database 

### ISSUE THREAD

**Issue by ritusha-r-ma** [CSCI-GA-2820-FA23-003/recommendations#2]
**As a** Database Developer
**I need** to design and implement a recommendation database schema in PostgreSQL
**So that** our system can efficiently store product recommendations for each user.
   
 ### Details and Assumptions
 * We will use PostgreSQL as our RDBMS.
 * The schema will have a single table, ProductRecommendations, that captures the relationship between a product and its recommended items.
 * product_id will be a foreign key to the main Products table which holds detailed product info.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a product has recommendations,
 When we look at the `ProductRecommendations` table,
 Then we should see columns like `product_id` (Foreign Key referencing `Products`), `product_name`, `recommended_product_id` (also a Foreign Key referencing `Products`), and `recommended_product_name`.
```

**Comment by yosemitii** [comment]
Maybe we an Entity-Relationship Diagram before we deploy the relational database.

**Comment by ritusha-r-ma** [comment]
Entity Schema Diagram Description:
Entities:
Products

Attributes:
product_id (Primary Key)
product_name

ProductRecommendations
Attributes:

product_id (Foreign Key referencing Products)
product_name
recommended_product_id (Foreign Key referencing Products)
recommended_product_name
