### ISSUE TITLE
Recommendation Relation Adding form 

### ISSUE THREAD

**Issue by HarbingerZou** [CSCI-GA-2820-FA23-003/recommendations#3]
As a database maintainer
I need a form that includes a select component that I can choose the product I want to set up recommendation,
and a list of select component with dynamic length that I can add the relevant products, which will be auto filled when the product is chosen.
So that I can add and update recommendation relations in data base. 
   
 ### Details and Assumptions
Expect a backend api point to accept this from when it's submitted.
Expect a relation model with the ID of a product as primary key and a list type field for storing relevant products.
   
 ### Acceptance Criteria  

 Given that the form is appropriately filled
 When the form is submitted.
 Then new relation should added to the database

**Comment by yujinlee0130** [comment]
Can we maybe split this up into two different issues and make it more concise?
